default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: mysql
  username: app_user
  password: app_pass
  port: 3306

development:
  <<: *default
  database: app_db

test:
  <<: *default
  database: app_db_test

production:
  <<: *default
  database: app_db
